### ISSUE TITLE
Null HandleLink when Aetheryte has space in name

### ISSUE THREAD

**Issue by m4chinations** [horoscope-dev/Dalamud.Divination.AetheryteLinkInChat#17]
Might a English specific issue.

When aetheryte has a space in the name, like "Sinus Lacrimarum" following error occurs:

```ERR: [Dinvination.AetheryteLinkInChat] HandleLink: aetheryte ("SinusLacrimarum") == null```

This issue does not happen with aetherytes without spaces in the name, e.g. "Tomra" 

Thank you for the plugin and the new updates. 🙇

**Comment by SlashNephy** [comment]
Hello.

Thank you for your bug report. I apologize for the lack of testing on the non-Japanese version.
I will fix the logic to work with the non-Japanese version.

In addition, non-localized strings will be translated in the future.

Best regards!

**Comment by SlashNephy** [comment]
Starting with commit https://github.com/horoscope-dev/Divination.AetheryteLinkInChat/commit/9abc81d3e0b11d814b0a56dbf1df9312fff5a713, the plugin no longer depends on TextPayload (i.e., the name of the aetherite). This should eliminate language-specific bugs.

You may see unexpected behavior due to the use of a low-level API (RawPayload). Please let me know if you have any further problems.

Thanks!!!

**Comment by SlashNephy** [comment]
As there seem to be no new bugs, I promoted this version to the stable repository.
